from __future__ import annotations

import re
from typing import Dict


_DEFAULT_ALIASES: Dict[str, str] = {
    # C# ecosystem
    "c sharp": "C#",
    "csharp": "C#",
    "c#": "C#",
    "c Sharp": "C#",
    "dotnet": ".NET",
    ".net": ".NET",
    ".net framework": ".NET Framework",
    ".net core": ".NET Core",
    ".net 5": ".NET 5",
    ".net 6": ".NET 6",
    ".net 7": ".NET 7",
    ".net 8": ".NET 8",
    "asp.net": "ASP.NET",
    "asp.net core": "ASP.NET Core",
    "aspnet": "ASP.NET",
    "aspnetcore": "ASP.NET Core",
    "entity framework": "Entity Framework",
    "entity framework core": "Entity Framework Core",
    "ef core": "Entity Framework Core",
    "ef": "Entity Framework",
    "blazor": "Blazor",
    "xamarin": "Xamarin",
    "maui": ".NET MAUI",
    ".net maui": ".NET MAUI",

    # JavaScript ecosystem
    "js": "JavaScript",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "react native": "React Native",
    "angular": "Angular",
    "angularjs": "AngularJS",
    "angular.js": "AngularJS",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "next": "Next.js",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nuxt": "Nuxt.js",
    "nuxtjs": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "svelte": "Svelte",
    "jquery": "jQuery",
    "redux": "Redux",
    "mobx": "MobX",
    "webpack": "Webpack",
    "vite": "Vite",
    "esbuild": "esbuild",
    "babel": "Babel",

    # Python ecosystem
    "python": "Python",
    "django": "Django",
    "django rest framework": "Django REST Framework",
    "drf": "Django REST Framework",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "uvicorn": "Uvicorn",
    "gunicorn": "Gunicorn",
    "celery": "Celery",
    "redis": "Redis",
    "sqlalchemy": "SQLAlchemy",
    "alembic": "Alembic",
    "pytest": "pytest",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "scipy": "SciPy",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "jupyter": "Jupyter",
    "jupyter notebook": "Jupyter Notebook",

    # Java ecosystem
    "java": "Java",
    "spring": "Spring",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "spring framework": "Spring Framework",
    "hibernate": "Hibernate",
    "junit": "JUnit",
    "kotlin": "Kotlin",
    "kotlin jvm": "Kotlin",

    # Go
    "go": "Go",
    "golang": "Go",

    # Rust
    "rust": "Rust",

    # PHP
    "php": "PHP",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "composer": "Composer",

    # Ruby
    "ruby": "Ruby",
    "ruby on rails": "Ruby on Rails",
    "rails": "Ruby on Rails",
    "ror": "Ruby on Rails",

    # Databases
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "psql": "PostgreSQL",
    "mysql": "MySQL",
    "mariadb": "MariaDB",
    "sql server": "SQL Server",
    "mssql": "SQL Server",
    "microsoft sql server": "SQL Server",
    "sqlite": "SQLite",
    "sqlite3": "SQLite",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "memcached": "Memcached",
    "elasticsearch": "Elasticsearch",
    "elastic": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "cosmos db": "Cosmos DB",
    "cosmosdb": "Cosmos DB",
    "firestore": "Firestore",
    "neo4j": "Neo4j",
    "couchdb": "CouchDB",
    "couchbase": "Couchbase",
    "influxdb": "InfluxDB",
    "timescaledb": "TimescaleDB",
    "supabase": "Supabase",
    "planetscale": "PlanetScale",

    # Cloud / DevOps
    "aws": "AWS",
    "amazon web services": "AWS",
    "ec2": "AWS EC2",
    "s3": "AWS S3",
    "lambda": "AWS Lambda",
    "azure": "Azure",
    "microsoft azure": "Azure",
    "gcp": "GCP",
    "google cloud": "GCP",
    "google cloud platform": "GCP",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "helm": "Helm",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "gitlab ci/cd": "GitLab CI",
    "circleci": "CircleCI",
    "circle ci": "CircleCI",
    "travis ci": "Travis CI",
    "argocd": "ArgoCD",
    "argo cd": "ArgoCD",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "datadog": "Datadog",
    "new relic": "New Relic",
    "cloudflare": "Cloudflare",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "heroku": "Heroku",
    "fly.io": "Fly.io",
    "digitalocean": "DigitalOcean",
    "digital ocean": "DigitalOcean",

    # Version control / tools
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "svn": "SVN",
    "subversion": "SVN",

    # Testing
    "jest": "Jest",
    "mocha": "Mocha",
    "chai": "Chai",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "selenium": "Selenium",
    "junit": "JUnit",
    "testng": "TestNG",
    "xunit": "xUnit",
    "nunit": "NUnit",
    "mstest": "MSTest",
    "pyunit": "PyUnit",
    "unittest": "unittest",
    "robot framework": "Robot Framework",
    "k6": "k6",
    "locust": "Locust",

    # Message queues / event streaming
    "rabbitmq": "RabbitMQ",
    "kafka": "Kafka",
    "apache kafka": "Apache Kafka",
    "activemq": "ActiveMQ",
    "nats": "NATS",
    "pulsar": "Apache Pulsar",
    "rabbit mq": "RabbitMQ",

    # API / protocols
    "rest": "REST",
    "restful": "REST",
    "rest api": "REST API",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "grpc": "gRPC",
    "websocket": "WebSocket",
    "websockets": "WebSocket",
    "soap": "SOAP",
    "http": "HTTP",
    "https": "HTTPS",
    "oauth": "OAuth",
    "oauth2": "OAuth 2.0",
    "jwt": "JWT",
    "openapi": "OpenAPI",
    "swagger": "Swagger",

    # Frontend tools
    "html": "HTML",
    "html5": "HTML5",
    "css": "CSS",
    "css3": "CSS3",
    "sass": "Sass",
    "scss": "SCSS",
    "less": "Less",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "Material UI",
    "mui": "Material UI",
    "chakra ui": "Chakra UI",
    "ant design": "Ant Design",
    "antd": "Ant Design",
    "styled components": "Styled Components",
    "emotion": "Emotion",

    # Mobile
    "flutter": "Flutter",
    "dart": "Dart",
    "swift": "Swift",
    "swiftui": "SwiftUI",
    "swift ui": "SwiftUI",
    "objective-c": "Objective-C",
    "android": "Android",
    "ios": "iOS",
    "ionic": "Ionic",
    "capacitor": "Capacitor",
    "cordova": "Cordova",

    # Data tools
    "airflow": "Apache Airflow",
    "apache airflow": "Apache Airflow",
    "spark": "Apache Spark",
    "apache spark": "Apache Spark",
    "hadoop": "Apache Hadoop",
    "kafka": "Kafka",
    "dbt": "dbt",
    "power bi": "Power BI",
    "tableau": "Tableau",
    "looker": "Looker",

    # Design patterns / concepts
    "mvc": "MVC",
    "mvvm": "MVVM",
    "mvp": "MVP",
    "cqrs": "CQRS",
    "event driven": "Event-Driven",
    "event-driven": "Event-Driven",
    "domain driven design": "DDD",
    "ddd": "DDD",

    # Misc tools
    "postman": "Postman",
    "insomnia": "Insomnia",
    "figma": "Figma",
    "sketch": "Sketch",
    "adobe xd": "Adobe XD",
    "notion": "Notion",
    "jira": "Jira",
    "confluence": "Confluence",
    "trello": "Trello",
    "slack": "Slack",
    "discord": "Discord",

    # Networking / protocols
    "dns": "DNS",
    "tcp": "TCP",
    "udp": "UDP",
    "ip": "IP",
    "vpn": "VPN",
    "lan": "LAN",
    "wan": "WAN",
    "load balancer": "Load Balancer",
    "nginx": "Nginx",
    "apache": "Apache",
    "apache http server": "Apache HTTP Server",
    "traefik": "Traefik",
    "haproxy": "HAProxy",
    "caddy": "Caddy",

    # Containers / virtualization
    "podman": "Podman",
    "virtualbox": "VirtualBox",
    "vmware": "VMware",
    "hyper-v": "Hyper-V",
    "wsl": "WSL",
    "windows subsystem for linux": "WSL",

    # OS
    "linux": "Linux",
    "ubuntu": "Ubuntu",
    "debian": "Debian",
    "centos": "CentOS",
    "redhat": "Red Hat",
    "red hat": "Red Hat",
    "alpine": "Alpine Linux",
    "alpine linux": "Alpine Linux",
    "arch linux": "Arch Linux",
    "macos": "macOS",
    "mac os": "macOS",
    "windows": "Windows",
    "unix": "Unix",
    "freebsd": "FreeBSD",

    # Scripting / shell
    "bash": "Bash",
    "shell": "Shell",
    "powershell": "PowerShell",
    "zsh": "Zsh",
    "fish": "Fish",
    "awk": "AWK",
    "sed": "sed",

    # Other languages
    "scala": "Scala",
    "groovy": "Groovy",
    "clojure": "Clojure",
    "erlang": "Erlang",
    "elixir": "Elixir",
    "haskell": "Haskell",
    "ocaml": "OCaml",
    "f#": "F#",
    "f sharp": "F#",
    "r": "R",
    "matlab": "MATLAB",
    "perl": "Perl",
    "lua": "Lua",
    "zig": "Zig",
    "nim": "Nim",
    "crystal": "Crystal",
    "julia": "Julia",
    "v": "V",
    "odin": "Odin",

    # Misc
    "rest api": "REST API",
    "web api": "Web API",
    "micro service": "Microservice",
    "micro-service": "Microservice",

    # AI / LLM
    "gen ai": "Generative AI",
    "generative ai": "Generative AI",
    "llm": "LLM",
    "large language models": "LLM",
    "large language model": "LLM",
    "langchain": "LangChain",
    "lang chain": "LangChain",
    "llamaindex": "LlamaIndex",
    "llama index": "LlamaIndex",
    "llama-index": "LlamaIndex",
    "openai": "OpenAI",
    "anthropic": "Anthropic",
    "claude": "Claude",
    "chatgpt": "ChatGPT",
    "gpt": "GPT",
    "gpt-4": "GPT-4",
    "gpt-3": "GPT-3",
    "gemini": "Gemini",
    "bard": "Bard",
    "copilot": "Copilot",
    "github copilot": "GitHub Copilot",
    "hugging face": "Hugging Face",
    "huggingface": "Hugging Face",
    "transformers": "Transformers",
    "rag": "RAG",
    "retrieval augmented generation": "RAG",
    "fine-tuning": "Fine-Tuning",
    "fine tuning": "Fine-Tuning",
    "finetuning": "Fine-Tuning",
    "vector databases": "Vector Database",
    "vector database": "Vector Database",
    "vector store": "Vector Database",
    "vector stores": "Vector Database",
    "pinecone": "Pinecone",
    "weaviate": "Weaviate",
    "chromadb": "ChromaDB",
    "chroma": "ChromaDB",
    "qdrant": "Qdrant",
    "milvus": "Milvus",
    "pgvector": "pgvector",
    "mcp": "MCP",
    "model context protocol": "MCP",
    "ai agents": "AI Agents",
    "ai agent": "AI Agent",
    "autogen": "AutoGen",
    "crewai": "CrewAI",
    "crew ai": "CrewAI",
    "langgraph": "LangGraph",
    "lang graph": "LangGraph",
    "prompt engineering": "Prompt Engineering",
    "prompting": "Prompt Engineering",
    "stable diffusion": "Stable Diffusion",
    "midjourney": "Midjourney",
    "dall-e": "DALL-E",
    "dalle": "DALL-E",
    "whisper": "Whisper",
    "ollama": "Ollama",
    "llama": "LLaMA",
    "llama 2": "LLaMA 2",
    "llama 3": "LLaMA 3",
    "mistral": "Mistral",
    "mixtral": "Mixtral",
    "groq": "Groq",
    "together ai": "Together AI",
    "replicate": "Replicate",

    # Testing / QA
    "qa": "QA",
    "quality assurance": "QA",
    "test automation": "Test Automation",
    "automated testing": "Test Automation",
    "e2e testing": "E2E Testing",
    "end to end testing": "E2E Testing",
    "integration testing": "Integration Testing",
    "unit testing": "Unit Testing",
    "load testing": "Load Testing",
    "performance testing": "Performance Testing",
    "security testing": "Security Testing",
    "penetration testing": "Penetration Testing",
    "pentest": "Penetration Testing",
    "sast": "SAST",
    "dast": "DAST",

    # Databases
    "memcached": "Memcached",
    "cockroachdb": "CockroachDB",
    "fauna": "Fauna",
    "arangodb": "ArangoDB",
    "meilisearch": "MeiliSearch",
    "typesense": "Typesense",

    # Data engineering
    "data pipeline": "Data Pipeline",
    "data warehouse": "Data Warehouse",
    "data lake": "Data Lake",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "redshift": "Redshift",
    "databricks": "Databricks",
    "flink": "Apache Flink",
    "spark streaming": "Spark Streaming",

    # Cloud / DevOps extra
    "pulumi": "Pulumi",
    "cdk": "AWS CDK",
    "cloudformation": "CloudFormation",
    "opentofu": "OpenTofu",
    "vault": "HashiCorp Vault",
    "consul": "HashiCorp Consul",
    "podman": "Podman",
    "lxc": "LXC",
    "vagrant": "Vagrant",
    "istio": "Istio",
    "service mesh": "Service Mesh",
    "api gateway": "API Gateway",

    # Web / Frontend extra
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "sass": "Sass",
    "scss": "SCSS",
    "less": "Less",
    "vite": "Vite",
    "webpack": "Webpack",
    "esbuild": "esbuild",
    "babel": "Babel",
    "storybook": "Storybook",
    "three.js": "Three.js",
    "webgl": "WebGL",
    "webassembly": "WebAssembly",
    "wasm": "WebAssembly",

    # Python extra
    "sqlalchemy": "SQLAlchemy",
    "alembic": "Alembic",


    # Extra tools
    "insomnia": "Insomnia",
    "gatling": "Gatling",
    "jmeter": "JMeter",
    "vitest": "Vitest",
    "graphql": "GraphQL",
    "apollo": "Apollo",
    "hasura": "Hasura",
    "webhook": "Webhook",
    "webhooks": "Webhook",
    "sse": "SSE",
    "server-sent events": "SSE",

    # Architecture extra
    "monolith": "Monolith",
    "modular monolith": "Modular Monolith",
    "microservices architecture": "Microservices",

    # Web3 / Blockchain
    "web3": "Web3",
    "blockchain": "Blockchain",
    "ethereum": "Ethereum",
    "solidity": "Solidity",
    "smart contracts": "Smart Contracts",
    "smart contract": "Smart Contracts",

    # IoT / Embedded

    # Frontend frameworks
    "sveltekit": "SvelteKit",
    "remix": "Remix",
    "astro": "Astro",
    "solidjs": "SolidJS",
    "solid js": "SolidJS",
    "qwik": "Qwik",
    "htmx": "HTMX",
    "hono": "Hono",
    "lit": "Lit",

    # JS backends
    "adonisjs": "AdonisJS",
    "adonis js": "AdonisJS",
    "hapi": "Hapi",
    "sails.js": "Sails.js",
    "sails": "Sails.js",
    "feathersjs": "FeathersJS",
    "feathers": "FeathersJS",
    "loopback": "LoopBack",

    # Java/JVM
    "quarkus": "Quarkus",
    "micronaut": "Micronaut",
    "helidon": "Helidon",
    "play framework": "Play Framework",
    "play": "Play Framework",
    "vert.x": "Vert.x",
    "vertx": "Vert.x",
    "dropwizard": "Dropwizard",
    "jakarta ee": "Jakarta EE",
    "jakarta": "Jakarta EE",

    # PHP
    "cakephp": "CakePHP",
    "cake php": "CakePHP",
    "yii": "Yii",
    "phalcon": "Phalcon",
    "lumen": "Lumen",

    # Ruby
    "hanami": "Hanami",
    "roda": "Roda",

    # Go
    "gin": "Gin",
    "fiber": "Fiber",
    "beego": "Beego",
    "chi": "Chi",
    "gorilla": "Gorilla",

    # Rust
    "actix": "Actix",
    "rocket": "Rocket",
    "axum": "Axum",
    "warp": "Warp",

    # Other backends
    "phoenix": "Phoenix",
    "ktor": "Ktor",
    "javalin": "Javalin",
    "vapor": "Vapor",

    # Mobile/Desktop
    "capacitor": "Capacitor",
    "nativescript": "NativeScript",
    "tauri": "Tauri",
    "electron": "Electron",

    # State/Data libs
    "zustand": "Zustand",
    "jotai": "Jotai",
    "recoil": "Recoil",
    "valtio": "Valtio",
    "pinia": "Pinia",
    "ngrx": "NgRx",
    "ng rx": "NgRx",
    "react query": "React Query",
    "tanstack query": "TanStack Query",
    "tanstack router": "TanStack Router",
    "swr": "SWR",
    "zod": "Zod",
    "react hook form": "React Hook Form",
    "formik": "Formik",
    "xstate": "XState",
    "immer": "Immer",

    # UI libraries
    "shadcn": "shadcn/ui",
    "shadcn/ui": "shadcn/ui",
    "radix ui": "Radix UI",
    "headless ui": "Headless UI",
    "daisyui": "daisyUI",
    "daisy ui": "daisyUI",
    "vuetify": "Vuetify",
    "quasar": "Quasar",
    "primevue": "PrimeVue",
    "primeng": "PrimeNG",
    "primereact": "PrimeReact",
    "bulma": "Bulma",

    # CSS
    "tailwind css": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind": "Tailwind CSS",

    # ORMs / DB tools
    "drizzle": "Drizzle ORM",
    "drizzle orm": "Drizzle ORM",
    "prisma": "Prisma",
    "typeorm": "TypeORM",
    "sequelize": "Sequelize",
    "mikroorm": "MikroORM",
    "knex": "Knex.js",
    "knex.js": "Knex.js",
    "jpa": "JPA",
    "mybatis": "MyBatis",
    "gorm": "GORM",
    "diesel": "Diesel",
    "seaorm": "SeaORM",
    "ecto": "Ecto",
    "activerecord": "ActiveRecord",

    # CMS
    "payload": "Payload CMS",
    "payload cms": "Payload CMS",
    "keystonejs": "KeystoneJS",
    "keystone js": "KeystoneJS",
    "redwoodjs": "RedwoodJS",
    "redwood js": "RedwoodJS",
    "blitz.js": "Blitz.js",
    "blitz": "Blitz.js",

    # Python data/AI
    "streamlit": "Streamlit",
    "gradio": "Gradio",
    "dash": "Dash",
    "polars": "Polars",
    "dask": "Dask",
    "ray": "Ray",
    "scrapy": "Scrapy",
    "beautiful soup": "Beautiful Soup",

    # AI/LLM
    "haystack": "Haystack",
    "langflow": "LangFlow",
    "vllm": "vLLM",
    "semantic kernel": "Semantic Kernel",
    "chainlit": "Chainlit",

    # Streaming/Data
    "apache flink": "Apache Flink",
    "flink": "Apache Flink",
    "prefect": "Prefect",
    "dagster": "Dagster",
    "kedro": "Kedro",

    # Game engines
    "godot": "Godot",
    "unity": "Unity",
    "unreal engine": "Unreal Engine",
    "unreal": "Unreal Engine",
    "bevy": "Bevy",
    "phaser": "Phaser",

    # Build tools
    "rollup": "Rollup",
    "parcel": "Parcel",
    "turbopack": "Turbopack",
    "swc": "SWC",
    "turborepo": "Turborepo",
    "nx": "Nx",
    "lerna": "Lerna",
    "bazel": "Bazel",
    "cmake": "CMake",

    # Linting/Formatting
    "eslint": "ESLint",
    "prettier": "Prettier",
    "biome": "Biome",
    "oxlint": "Oxlint",
    "ruff": "Ruff",
    "black": "Black",
    "mypy": "Mypy",
    "pyright": "Pyright",
    "husky": "Husky",
    "lint-staged": "Lint-staged",

    # Monitoring/Observability
    "sentry": "Sentry",
    "splunk": "Splunk",
    "kibana": "Kibana",
    "logstash": "Logstash",
    "jaeger": "Jaeger",
    "zipkin": "Zipkin",
    "opentelemetry": "OpenTelemetry",
    "otel": "OpenTelemetry",

    # Infra
    "nomad": "Nomad",
    "crossplane": "Crossplane",
    "packer": "Packer",
    "minikube": "Minikube",
    "k3s": "k3s",
    "rancher": "Rancher",
    "knative": "Knative",

    # Security
    "snyk": "Snyk",
    "sonarqube": "SonarQube",
    "semgrep": "Semgrep",
    "codeql": "CodeQL",
    "trivy": "Trivy",

    # Testing extras
    "artillery": "Artillery",
    "wiremock": "WireMock",
    "mockoon": "Mockoon",
    "vitest": "Vitest",
    "supertest": "Supertest",
    "msw": "MSW",
    "storybook": "Storybook",
    "puppeteer": "Puppeteer",

    # Databases
    "oracle": "Oracle Database",
    "oracle database": "Oracle Database",
    "microsoft sql server": "SQL Server",
    "mssql": "SQL Server",
    "clickhouse": "ClickHouse",
    "surrealdb": "SurrealDB",
    "surreal db": "SurrealDB",
    "edgedb": "EdgeDB",
    "edge db": "EdgeDB",
    "turso": "Turso",
    "realm": "Realm",
    "faunadb": "FaunaDB",
    "fauna db": "FaunaDB",
    "scylladb": "ScyllaDB",
    "hbase": "HBase",
    "tidb": "TiDB",
    "yugabytedb": "YugabyteDB",
    "rethinkdb": "RethinkDB",
    "minio": "MinIO",
    "rocksdb": "RocksDB",
    "leveldb": "LevelDB",
    "etcd": "etcd",
    "lancedb": "LanceDB",
    "mongodb atlas": "MongoDB Atlas",

    # Servers
    "bun": "Bun",
    "deno": "Deno",
    "tomcat": "Tomcat",
    "apache tomcat": "Tomcat",
    "wildfly": "WildFly",
    "jboss": "JBoss",
    "glassfish": "GlassFish",
    "jetty": "Jetty",
    "kong": "Kong",
    "envoy": "Envoy",
    "linkerd": "Linkerd",

    # Platforms
    "railway": "Railway",
    "render": "Render",
    "fly.io": "Fly.io",
    "fly io": "Fly.io",
    "cloudflare workers": "Cloudflare Workers",
    "cloudflare pages": "Cloudflare Pages",
    "aws lambda": "AWS Lambda",
    "aws ec2": "AWS EC2",
    "aws s3": "AWS S3",
    "aws rds": "AWS RDS",
    "aws cloudfront": "AWS CloudFront",
    "azure functions": "Azure Functions",
    "azure devops": "Azure DevOps",
    "google cloud run": "Google Cloud Run",
    "google app engine": "Google App Engine",
    "linear": "Linear",
    "miro": "Miro",
    "auth0": "Auth0",
    "okta": "Okta",
    "clerk": "Clerk",
    "sanity": "Sanity",
    "contentful": "Contentful",
    "strapi": "Strapi",
    "algolia": "Algolia",
    "shopify": "Shopify",
    "woocommerce": "WooCommerce",
    "magento": "Magento",
    "salesforce": "Salesforce",
    "hubspot": "HubSpot",
    "sendgrid": "SendGrid",
    "mailgun": "Mailgun",
    "twilio": "Twilio",
    "cloudinary": "Cloudinary",
    "segment": "Segment",
    "mixpanel": "Mixpanel",
    "amplitude": "Amplitude",
    "posthog": "PostHog",
    "wordpress": "WordPress",
    "drupal": "Drupal",
    "webflow": "Webflow",
    "appwrite": "Appwrite",
    "pocketbase": "Pocketbase",
    "directus": "Directus",
    "upstash": "Upstash",
    "neon": "Neon",

    # Dev tools / editors
    "codesandbox": "CodeSandbox",
    "stackblitz": "StackBlitz",
    "replit": "Replit",
    "gitpod": "Gitpod",
    "bruno": "Bruno",
    "hoppscotch": "Hoppscotch",
    "httpie": "HTTPie",
    "fastlane": "Fastlane",
    "bitrise": "Bitrise",
    "codemagic": "Codemagic",
    "lighthouse": "Lighthouse",
    "dbeaver": "DBeaver",
    "pgadmin": "pgAdmin",

    # Web3
    "web3.js": "Web3.js",
    "web3js": "Web3.js",
    "ethers.js": "Ethers.js",
    "ethers": "Ethers.js",
    "viem": "Viem",
    "wagmi": "Wagmi",

    # Productivity / Office (O*NET)
    "microsoft excel": "Microsoft Excel",
    "excel": "Microsoft Excel",
    "microsoft word": "Microsoft Word",
    "word": "Microsoft Word",
    "microsoft powerpoint": "Microsoft PowerPoint",
    "powerpoint": "Microsoft PowerPoint",
    "microsoft outlook": "Microsoft Outlook",
    "outlook": "Microsoft Outlook",
    "microsoft teams": "Microsoft Teams",
    "teams": "Microsoft Teams",
    "microsoft sharepoint": "Microsoft SharePoint",
    "sharepoint": "Microsoft SharePoint",
    "microsoft project": "Microsoft Project",
    "microsoft visio": "Microsoft Visio",
    "visio": "Microsoft Visio",
    "google docs": "Google Docs",
    "google sheets": "Google Sheets",
    "google analytics": "Google Analytics",
    "google workspace": "Google Workspace",
    "microsoft office": "Microsoft Office",
    "office 365": "Microsoft 365",
    "microsoft 365": "Microsoft 365",

    # Business / Enterprise (O*NET)
    "salesforce": "Salesforce",
    "sap": "SAP",
    "sap erp": "SAP ERP",
    "hubspot": "HubSpot",
    "workday": "Workday",
    "servicenow": "ServiceNow",
    "oracle database": "Oracle Database",
    "oracle": "Oracle Database",
    "oracle peoplesoft": "Oracle PeopleSoft",
    "peoplesoft": "Oracle PeopleSoft",
    "quickbooks": "QuickBooks",
    "intuit quickbooks": "QuickBooks",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "slack": "Slack",
    "zoom": "Zoom",
    "asana": "Asana",
    "marketo": "Marketo",

    # Creative / Design (O*NET)
    "adobe photoshop": "Adobe Photoshop",
    "photoshop": "Adobe Photoshop",
    "adobe illustrator": "Adobe Illustrator",
    "illustrator": "Adobe Illustrator",
    "adobe indesign": "Adobe InDesign",
    "indesign": "Adobe InDesign",
    "adobe after effects": "Adobe After Effects",
    "after effects": "Adobe After Effects",
    "adobe creative cloud": "Adobe Creative Cloud",
    "creative cloud": "Adobe Creative Cloud",
    "adobe xd": "Adobe XD",
    "adobe premiere pro": "Adobe Premiere Pro",
    "premiere pro": "Adobe Premiere Pro",
    "adobe lightroom": "Adobe Lightroom",
    "lightroom": "Adobe Lightroom",
    "figma": "Figma",
    "sketch": "Sketch",
    "canva": "Canva",
    "invision": "InVision",

    # CAD / Engineering (O*NET)
    "autocad": "AutoCAD",
    "autodesk autocad": "AutoCAD",
    "revit": "Revit",
    "autodesk revit": "Revit",
    "solidworks": "SolidWorks",
    "dassault solidworks": "SolidWorks",
    "autodesk civil 3d": "AutoCAD Civil 3D",

    # GIS (O*NET)
    "arcgis": "ArcGIS",
    "esri arcgis": "ArcGIS",
    "qgis": "QGIS",

    # Video (O*NET)
    "davinci resolve": "DaVinci Resolve",
    "final cut pro": "Final Cut Pro",
    "adobe premiere": "Adobe Premiere Pro",

    # Security (O*NET)
    "kali linux": "Kali Linux",
    "nmap": "Nmap",
    "metasploit": "Metasploit",
    "burp suite": "Burp Suite",
    "nessus": "Nessus",

    # Misc libs
    "framer motion": "Framer Motion",
    "framer": "Framer Motion",
    "gsap": "GSAP",
    "socket.io": "Socket.io",
    "socket io": "Socket.io",
    "three.js": "Three.js",
    "three js": "Three.js",
    "d3.js": "D3.js",
    "d3": "D3.js",
    "chart.js": "Chart.js",
    "chart js": "Chart.js",
    "recharts": "Recharts",
    "passport.js": "Passport.js",
    "passport": "Passport.js",
    "pino": "Pino",
    "winston": "Winston",
    "cheerio": "Cheerio",
    "sharp": "Sharp",
    "mediapipe": "MediaPipe",
    "tensorflow.js": "TensorFlow.js",
    "tfjs": "TensorFlow.js",
    "sidekiq": "Sidekiq",
    "bull": "Bull",
    "bullmq": "BullMQ",
    "swagger": "Swagger",
    "openapi": "OpenAPI",
    "sklearn": "scikit-learn",
    "tf": "TensorFlow",
    "pg": "PostgreSQL",
    "postgres": "PostgreSQL",
    "node": "Node.js",
    "react": "React",
    "vue": "Vue.js",
    "angular": "Angular",
    "svelte": "Svelte",
    "next": "Next.js",
    "nuxt": "Nuxt.js",
    "remix": "Remix",
    "astro": "Astro",
}


class SkillNormalizer:
    def __init__(self, extra_aliases: Optional[Dict[str, str]] = None):
        self._aliases = dict(_DEFAULT_ALIASES)
        if extra_aliases:
            self._aliases.update({k.lower(): v for k, v in extra_aliases.items()})

    def normalize(self, name: str) -> str:
        key = name.strip().lower()
        if key in self._aliases:
            return self._aliases[key]
        return name.strip()


_normalizer: Optional[SkillNormalizer] = None


def get_normalizer(extra_aliases: Optional[Dict[str, str]] = None) -> SkillNormalizer:
    global _normalizer
    if _normalizer is None:
        _normalizer = SkillNormalizer(extra_aliases)
    return _normalizer
