from __future__ import annotations

import re
from typing import Dict


_DEFAULT_ALIASES: Dict[str, str] = {
    # C# ecosystem
    "c sharp": "C#",
    "csharp": "C#",
    "c#": "C#",
    "c Sharp": "C#",
    "dotnet": ".NET",
    ".net": ".NET",
    ".net framework": ".NET Framework",
    ".net core": ".NET Core",
    ".net 5": ".NET 5",
    ".net 6": ".NET 6",
    ".net 7": ".NET 7",
    ".net 8": ".NET 8",
    "asp.net": "ASP.NET",
    "asp.net core": "ASP.NET Core",
    "aspnet": "ASP.NET",
    "aspnetcore": "ASP.NET Core",
    "entity framework": "Entity Framework",
    "entity framework core": "Entity Framework Core",
    "ef core": "Entity Framework Core",
    "ef": "Entity Framework",
    "blazor": "Blazor",
    "xamarin": "Xamarin",
    "maui": ".NET MAUI",
    ".net maui": ".NET MAUI",

    # JavaScript ecosystem
    "js": "JavaScript",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "react native": "React Native",
    "angular": "Angular",
    "angularjs": "AngularJS",
    "angular.js": "AngularJS",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "next": "Next.js",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nuxt": "Nuxt.js",
    "nuxtjs": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "svelte": "Svelte",
    "jquery": "jQuery",
    "redux": "Redux",
    "mobx": "MobX",
    "webpack": "Webpack",
    "vite": "Vite",
    "esbuild": "esbuild",
    "babel": "Babel",
    "npm": "npm",
    "yarn": "Yarn",
    "pnpm": "pnpm",

    # Python ecosystem
    "python": "Python",
    "django": "Django",
    "django rest framework": "Django REST Framework",
    "drf": "Django REST Framework",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "uvicorn": "Uvicorn",
    "gunicorn": "Gunicorn",
    "celery": "Celery",
    "redis": "Redis",
    "sqlalchemy": "SQLAlchemy",
    "alembic": "Alembic",
    "pytest": "pytest",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "scipy": "SciPy",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "jupyter": "Jupyter",
    "jupyter notebook": "Jupyter Notebook",
    "pip": "pip",
    "poetry": "Poetry",
    "conda": "Conda",

    # Java ecosystem
    "java": "Java",
    "spring": "Spring",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "spring framework": "Spring Framework",
    "hibernate": "Hibernate",
    "maven": "Maven",
    "gradle": "Gradle",
    "junit": "JUnit",
    "kotlin": "Kotlin",
    "kotlin jvm": "Kotlin",

    # Go
    "go": "Go",
    "golang": "Go",

    # Rust
    "rust": "Rust",
    "cargo": "Cargo",

    # PHP
    "php": "PHP",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "composer": "Composer",

    # Ruby
    "ruby": "Ruby",
    "ruby on rails": "Ruby on Rails",
    "rails": "Ruby on Rails",
    "ror": "Ruby on Rails",

    # Databases
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "psql": "PostgreSQL",
    "mysql": "MySQL",
    "mariadb": "MariaDB",
    "sql server": "SQL Server",
    "mssql": "SQL Server",
    "microsoft sql server": "SQL Server",
    "sqlite": "SQLite",
    "sqlite3": "SQLite",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "memcached": "Memcached",
    "elasticsearch": "Elasticsearch",
    "elastic": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "cosmos db": "Cosmos DB",
    "cosmosdb": "Cosmos DB",
    "firestore": "Firestore",
    "neo4j": "Neo4j",
    "couchdb": "CouchDB",
    "couchbase": "Couchbase",
    "influxdb": "InfluxDB",
    "timescaledb": "TimescaleDB",
    "supabase": "Supabase",
    "planetscale": "PlanetScale",

    # Cloud / DevOps
    "aws": "AWS",
    "amazon web services": "AWS",
    "ec2": "AWS EC2",
    "s3": "AWS S3",
    "lambda": "AWS Lambda",
    "azure": "Azure",
    "microsoft azure": "Azure",
    "gcp": "GCP",
    "google cloud": "GCP",
    "google cloud platform": "GCP",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "helm": "Helm",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "gitlab ci/cd": "GitLab CI",
    "circleci": "CircleCI",
    "circle ci": "CircleCI",
    "travis ci": "Travis CI",
    "argocd": "ArgoCD",
    "argo cd": "ArgoCD",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "datadog": "Datadog",
    "new relic": "New Relic",
    "cloudflare": "Cloudflare",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "heroku": "Heroku",
    "fly.io": "Fly.io",
    "digitalocean": "DigitalOcean",
    "digital ocean": "DigitalOcean",

    # Version control / tools
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "svn": "SVN",
    "subversion": "SVN",

    # Testing
    "jest": "Jest",
    "mocha": "Mocha",
    "chai": "Chai",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "selenium": "Selenium",
    "junit": "JUnit",
    "testng": "TestNG",
    "xunit": "xUnit",
    "nunit": "NUnit",
    "mstest": "MSTest",
    "pyunit": "PyUnit",
    "unittest": "unittest",
    "robot framework": "Robot Framework",
    "k6": "k6",
    "locust": "Locust",

    # Message queues / event streaming
    "rabbitmq": "RabbitMQ",
    "kafka": "Kafka",
    "apache kafka": "Apache Kafka",
    "activemq": "ActiveMQ",
    "nats": "NATS",
    "pulsar": "Apache Pulsar",
    "rabbit mq": "RabbitMQ",

    # API / protocols
    "rest": "REST",
    "restful": "REST",
    "rest api": "REST API",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "grpc": "gRPC",
    "websocket": "WebSocket",
    "websockets": "WebSocket",
    "soap": "SOAP",
    "http": "HTTP",
    "https": "HTTPS",
    "oauth": "OAuth",
    "oauth2": "OAuth 2.0",
    "jwt": "JWT",
    "openapi": "OpenAPI",
    "swagger": "Swagger",

    # Frontend tools
    "html": "HTML",
    "html5": "HTML5",
    "css": "CSS",
    "css3": "CSS3",
    "sass": "Sass",
    "scss": "SCSS",
    "less": "Less",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "Material UI",
    "mui": "Material UI",
    "chakra ui": "Chakra UI",
    "ant design": "Ant Design",
    "antd": "Ant Design",
    "styled components": "Styled Components",
    "emotion": "Emotion",

    # Mobile
    "flutter": "Flutter",
    "dart": "Dart",
    "swift": "Swift",
    "swiftui": "SwiftUI",
    "swift ui": "SwiftUI",
    "objective-c": "Objective-C",
    "android": "Android",
    "ios": "iOS",
    "ionic": "Ionic",
    "capacitor": "Capacitor",
    "cordova": "Cordova",

    # Data / ML
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "dl": "Deep Learning",
    "nlp": "NLP",
    "natural language processing": "NLP",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "data science": "Data Science",
    "data engineering": "Data Engineering",
    "data analysis": "Data Analysis",
    "data analytics": "Data Analytics",
    "etl": "ETL",
    "airflow": "Apache Airflow",
    "apache airflow": "Apache Airflow",
    "spark": "Apache Spark",
    "apache spark": "Apache Spark",
    "hadoop": "Apache Hadoop",
    "kafka": "Kafka",
    "dbt": "dbt",
    "power bi": "Power BI",
    "tableau": "Tableau",
    "looker": "Looker",

    # Security
    "owasp": "OWASP",
    "penetration testing": "Penetration Testing",
    "pentesting": "Penetration Testing",
    "cybersecurity": "Cybersecurity",
    "infosec": "Information Security",
    "ssl": "SSL",
    "tls": "TLS",
    "waf": "WAF",
    "siem": "SIEM",

    # Methodologies / concepts
    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "ci/cd": "CI/CD",
    "ci cd": "CI/CD",
    "cicd": "CI/CD",
    "devops": "DevOps",
    "microservices": "Microservices",
    "microservices architecture": "Microservices",
    "serverless": "Serverless",
    "saas": "SaaS",
    "paas": "PaaS",
    "iaas": "IaaS",
    "tdd": "TDD",
    "test driven development": "TDD",
    "bdd": "BDD",
    "behavior driven development": "BDD",
    "solid": "SOLID",
    "oop": "OOP",
    "object oriented programming": "OOP",
    "functional programming": "Functional Programming",

    # Design patterns / concepts
    "mvc": "MVC",
    "mvvm": "MVVM",
    "mvp": "MVP",
    "cqrs": "CQRS",
    "event driven": "Event-Driven",
    "event-driven": "Event-Driven",
    "domain driven design": "DDD",
    "ddd": "DDD",

    # Misc tools
    "postman": "Postman",
    "insomnia": "Insomnia",
    "figma": "Figma",
    "sketch": "Sketch",
    "adobe xd": "Adobe XD",
    "notion": "Notion",
    "jira": "Jira",
    "confluence": "Confluence",
    "trello": "Trello",
    "slack": "Slack",
    "discord": "Discord",
    "vscode": "VS Code",
    "visual studio": "Visual Studio",
    "visual studio code": "VS Code",
    "intellij": "IntelliJ IDEA",
    "intellij idea": "IntelliJ IDEA",
    "pycharm": "PyCharm",
    "webstorm": "WebStorm",
    "vim": "Vim",
    "neovim": "Neovim",
    "emacs": "Emacs",

    # Networking / protocols
    "dns": "DNS",
    "tcp": "TCP",
    "udp": "UDP",
    "ip": "IP",
    "vpn": "VPN",
    "lan": "LAN",
    "wan": "WAN",
    "load balancer": "Load Balancer",
    "nginx": "Nginx",
    "apache": "Apache",
    "apache http server": "Apache HTTP Server",
    "traefik": "Traefik",
    "haproxy": "HAProxy",
    "caddy": "Caddy",

    # Containers / virtualization
    "podman": "Podman",
    "virtualbox": "VirtualBox",
    "vmware": "VMware",
    "hyper-v": "Hyper-V",
    "wsl": "WSL",
    "windows subsystem for linux": "WSL",

    # OS
    "linux": "Linux",
    "ubuntu": "Ubuntu",
    "debian": "Debian",
    "centos": "CentOS",
    "redhat": "Red Hat",
    "red hat": "Red Hat",
    "alpine": "Alpine Linux",
    "alpine linux": "Alpine Linux",
    "arch linux": "Arch Linux",
    "macos": "macOS",
    "mac os": "macOS",
    "windows": "Windows",
    "unix": "Unix",
    "freebsd": "FreeBSD",

    # Scripting / shell
    "bash": "Bash",
    "shell": "Shell",
    "powershell": "PowerShell",
    "zsh": "Zsh",
    "fish": "Fish",
    "awk": "AWK",
    "sed": "sed",

    # Other languages
    "scala": "Scala",
    "groovy": "Groovy",
    "clojure": "Clojure",
    "erlang": "Erlang",
    "elixir": "Elixir",
    "haskell": "Haskell",
    "ocaml": "OCaml",
    "f#": "F#",
    "f sharp": "F#",
    "r": "R",
    "matlab": "MATLAB",
    "perl": "Perl",
    "lua": "Lua",
    "zig": "Zig",
    "nim": "Nim",
    "crystal": "Crystal",
    "julia": "Julia",
    "v": "V",
    "odin": "Odin",

    # Misc
    "rest api": "REST API",
    "web api": "Web API",
    "micro service": "Microservice",
    "micro-service": "Microservice",
    "full stack": "Full-Stack",
    "fullstack": "Full-Stack",
    "full-stack": "Full-Stack",
    "back end": "Backend",
    "backend": "Backend",
    "back-end": "Backend",
    "front end": "Frontend",
    "frontend": "Frontend",
    "front-end": "Frontend",
    "devops": "DevOps",
    "dev ops": "DevOps",
    "site reliability": "SRE",
    "sre": "SRE",
    "platform engineering": "Platform Engineering",
    "cloud native": "Cloud-Native",
    "cloud-native": "Cloud-Native",
    "low code": "Low-Code",
    "low-code": "Low-Code",
    "no code": "No-Code",
    "no-code": "No-Code",
}


class SkillNormalizer:
    def __init__(self, extra_aliases: Optional[Dict[str, str]] = None):
        self._aliases = dict(_DEFAULT_ALIASES)
        if extra_aliases:
            self._aliases.update({k.lower(): v for k, v in extra_aliases.items()})

    def normalize(self, name: str) -> str:
        key = name.strip().lower()
        if key in self._aliases:
            return self._aliases[key]
        return name.strip()


_normalizer: Optional[SkillNormalizer] = None


def get_normalizer(extra_aliases: Optional[Dict[str, str]] = None) -> SkillNormalizer:
    global _normalizer
    if _normalizer is None:
        _normalizer = SkillNormalizer(extra_aliases)
    return _normalizer
